Repository ispras/dedoc, pull requests merged in 2024-09, with the labels that each got.

#483 TLDR-748 structure pattern
  .flake8
  .github/workflows/docs.yaml
  .pre-commit-config.yaml
  dedoc/api/api_args.py
  dedoc/api/web/index.html
  dedoc/data_structures/line_metadata.py
  dedoc/data_structures/line_with_meta.py
  dedoc/readers/docx_reader/line_with_meta_converter.py
  dedoc/readers/pdf_reader/data_classes/line_with_location.py
  dedoc/readers/pdf_reader/pdf_auto_reader/pdf_auto_reader.py
  dedoc/readers/pdf_reader/pdf_base_reader.py
  dedoc/readers/pdf_reader/pdf_txtlayer_reader/pdf_tabby_reader.py
  dedoc/readers/pdf_reader/utils/line_object_linker.py
  dedoc/readers/pptx_reader/paragraph.py
  dedoc/readers/txt_reader/raw_text_reader.py
  dedoc/structure_extractors/concrete_structure_extractors/default_structure_extractor.py
  dedoc/structure_extractors/feature_extractors/list_features/prefix/bracket_roman_prefix.py
  dedoc/structure_extractors/feature_extractors/list_features/prefix/roman_prefix.py
  dedoc/structure_extractors/hierarchy_level_builders/diploma_builder/body_builder.py
  dedoc/structure_extractors/patterns/__init__.py
  dedoc/structure_extractors/patterns/abstract_pattern.py
  dedoc/structure_extractors/patterns/bracket_list_pattern.py
  dedoc/structure_extractors/patterns/bracket_roman_list_pattern.py
  dedoc/structure_extractors/patterns/bullet_list_pattern.py
  dedoc/structure_extractors/patterns/dotted_list_pattern.py
  dedoc/structure_extractors/patterns/letter_list_pattern.py
  dedoc/structure_extractors/patterns/pattern_composition.py
  dedoc/structure_extractors/patterns/regexp_pattern.py
  dedoc/structure_extractors/patterns/roman_list_pattern.py
  dedoc/structure_extractors/patterns/start_word_pattern.py
  dedoc/structure_extractors/patterns/tag_header_pattern.py
  dedoc/structure_extractors/patterns/tag_list_pattern.py
  dedoc/structure_extractors/patterns/tag_pattern.py
  dedoc/structure_extractors/patterns/utils.py
  dedoc/utils/parameter_utils.py
  docs/source/_static/code_examples/dedoc_using_patterns_tutorial.py
  docs/source/_static/code_examples/test_dir/law.pdf
  docs/source/_static/code_examples/test_dir/law.png
  docs/source/_static/code_examples/test_dir/with_tags.docx
  docs/source/_static/code_examples/test_dir/with_tags.png
  docs/source/conf.py
  docs/source/dedoc_api_usage/api.rst
  docs/source/getting_started/usage.rst
  docs/source/index.rst
  docs/source/modules/structure_extractors.rst
  docs/source/parameters/pdf_handling.rst
  docs/source/parameters/structure_type.rst
  docs/source/readers_output/line_types.rst
  docs/source/structure_types/other.rst
  docs/source/tutorials/add_new_doc_format.rst
  docs/source/tutorials/add_new_structure_type/features_extraction.rst
  docs/source/tutorials/using_patterns.rst
  pyproject.toml
  tests/api_tests/test_api_doctype_default.py
  tests/api_tests/test_api_format_txt.py
  tests/unit_tests/test_doctype_default_structure_extractor.py
Labels: documentation, enhancement

#495 TLDR-809 fix docx numeration bug
  dedoc/readers/docx_reader/numbering_extractor.py
Labels: bug

#496 TLDR-807 ignore gost frame in PdfTxtlayerReader
  dedoc/readers/pdf_reader/pdf_base_reader.py
  dedoc/readers/pdf_reader/pdf_image_reader/table_recognizer/gost_frame_recognizer.py
  dedoc/readers/pdf_reader/pdf_txtlayer_reader/pdf_txtlayer_reader.py
  docs/source/dedoc_api_usage/api.rst
  docs/source/parameters/pdf_handling.rst
  tests/api_tests/test_api_module_table_recognizer.py
  tests/data/tables/gost_multipage_table_2.pdf
  tests/unit_tests/test_module_gost_frame_recognizer.py
Labels: enhancement

#499 TLDR-774 fix bug in numbering styles
  dedoc/readers/docx_reader/numbering_extractor.py
Labels: bug
